#!/bin/bash -e
#
# Copyright 2021 Braden (R) Portuguese company
#
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at http://mozilla.org/MPL/2.0/.

# The -e flag instructs the script to exit on error.
# https://www.gnu.org/software/bash/manual/bash.html#Modifying-Shell-Behavior

wd=$(pwd)
# Get the project absolute path
projectdir=$(git rev-parse --show-toplevel || \
  { >&2 echo "ERROR: Git repository directory not found in $wd"; exit 255; })

# Change this path if you want your script in another location
# < /dev/tty for the python to have input
"$projectdir"/.git/hooks/pre-commit-copy-config.py < /dev/tty

#clean the variables
unset wd projectdir
