#!/bin/bash -e
# The -e flag instructs the script to exit on error.
# https://www.gnu.org/software/bash/manual/bash.html#Modifying-Shell-Behavior

wd=$(pwd)
projectdir=$(git rev-parse --show-toplevel || { >&2 echo "ERROR: Git repository directory not found in $wd"; exit 255; })

"$projectdir"/.git/hooks/pre-commit-settings-gradle.py < /dev/tty

